import { lazy } from 'react'

/**
 * META — single source of truth for the portfolio grid.
 * Each entry drives a card on the home page and the routing to /site/:slug.
 *
 * palette: { bg, fg, accent, accent2 } — used by the card mini-mockup.
 * font:    { display, body }           — Tailwind font utilities (font-<display>).
 * group:   filter bucket on the portfolio.
 * category: specific sector label shown on the card.
 */
export const META = [
  {
    slug: 'filipitsch',
    name: 'Filipitsch — Terapia Activa',
    short: 'Filipitsch',
    category: 'Terapia & Bem-estar',
    group: 'Saúde & Beleza',
    tagline: 'Profissionais de saúde ao seu inteiro dispor.',
    location: 'Calçada do Tojal 28A · Benfica',
    year: '2025',
    palette: { bg: '#0E3B34', fg: '#F4F0E4', accent: '#CBA35C', accent2: '#7FB39B' },
    font: { display: 'fraunces', body: 'nunito' },
  },
  {
    slug: 'reparacao-tv-lisboa',
    name: 'Reparação TV Lisboa',
    short: 'Reparação TV',
    category: 'Reparação de TV',
    group: 'Casa & Clima',
    tagline: 'Especialistas exclusivos em reparação de televisores.',
    location: 'Calçada do Tojal 53B · Lisboa',
    year: '2025',
    palette: { bg: '#FFFFFF', fg: '#0F1B2D', accent: '#2E7DF6', accent2: '#0B8C73' },
    font: { display: 'space', body: 'sans' },
  },
  {
    slug: 'pedrita-studio',
    name: 'Pedrita Studio',
    short: 'Pedrita',
    category: 'Estúdio de Design',
    group: 'Serviços & Negócios',
    tagline: 'Estúdio de design multidisciplinar em Lisboa desde 2005.',
    location: 'Calçada do Tojal 71A · Lisboa',
    year: '2025',
    palette: { bg: '#F1EEE6', fg: '#15181D', accent: '#2B5BD7', accent2: '#E0B23B' },
    font: { display: 'syne', body: 'sans' },
  },
  {
    slug: 'tecnico-frio',
    name: 'Técnico Frio',
    short: 'Técnico Frio',
    category: 'Frio & Ar Condicionado',
    group: 'Casa & Clima',
    tagline: 'Reparação de ar condicionado e frigoríficos na Grande Lisboa.',
    location: 'Calçada do Tojal 03 · Lisboa',
    year: '2025',
    palette: { bg: '#F1F8FC', fg: '#0B2536', accent: '#0B6CC0', accent2: '#16B5C9' },
    font: { display: 'outfit', body: 'sans' },
  },
  {
    slug: 'nipolandia',
    name: 'Nipolândia',
    short: 'Nipolândia',
    category: 'Climatização AVAC',
    group: 'Casa & Clima',
    tagline: 'Climatização e ventilação com rigor desde 1977.',
    location: 'R. Jorge Barradas 49B · Benfica',
    year: '2025',
    palette: { bg: '#F2F6FC', fg: '#0A2E5C', accent: '#2C7BE5', accent2: '#FF7F00' },
    font: { display: 'archivo', body: 'sans' },
  },
  {
    slug: 'farol-vibrante',
    name: 'Farol Vibrante — Construções LSF',
    short: 'Farol Vibrante',
    category: 'Construção LSF',
    group: 'Construção & Indústria',
    tagline: 'Construção em Light Steel Framing — mais rápida, leve e sustentável.',
    location: 'R. Cmte. Henrique Maya 7C · Lisboa',
    year: '2025',
    palette: { bg: '#F7F8FA', fg: '#14181D', accent: '#F2A33C', accent2: '#64727F' },
    font: { display: 'sora', body: 'sans' },
  },
  {
    slug: 'fornoportugal',
    name: 'Fornoportugal — Refractários',
    short: 'Fornoportugal',
    category: 'Refractários Industriais',
    group: 'Construção & Indústria',
    tagline: 'Engenharia de fornos refractários para a indústria, no mundo inteiro.',
    location: 'R. das Pedralvas 23A · Lisboa',
    year: '2025',
    palette: { bg: '#F7F5F1', fg: '#1B2540', accent: '#D11F2A', accent2: '#1F2D5E' },
    font: { display: 'oswald', body: 'sans' },
  },
  {
    slug: 'iri',
    name: 'IRI — Isolamentos e Revestimentos',
    short: 'IRI',
    category: 'Isolamentos & Revestimentos',
    group: 'Construção & Indústria',
    tagline: 'Isolamentos, revestimentos e impermeabilização há 30 anos.',
    location: 'R. Jorge Barradas 37A · Lisboa',
    year: '2025',
    palette: { bg: '#F4F6F8', fg: '#14202B', accent: '#007A79', accent2: '#FAA734' },
    font: { display: 'manrope', body: 'sans' },
  },
  {
    slug: 'conta-100',
    name: 'Conta 100% — Contabilidade',
    short: 'Conta 100%',
    category: 'Contabilidade',
    group: 'Serviços & Negócios',
    tagline: 'Cuidamos da sua contabilidade. Fazemos crescer o seu negócio.',
    location: 'R. Lucília Simões 1A · Benfica',
    year: '2025',
    palette: { bg: '#F4F8F6', fg: '#16363B', accent: '#0B7C88', accent2: '#3AC2CF' },
    font: { display: 'jakarta', body: 'sans' },
  },
  {
    slug: 'rui-dinis',
    name: 'Rui Dinis, Lda.',
    short: 'Rui Dinis',
    category: 'Eletrónica Industrial',
    group: 'Construção & Indústria',
    tagline: 'Máquinas de alta frequência e ultra-sons. Assistência à indústria.',
    location: 'R. Rogério Amaral 6A · Benfica',
    year: '2025',
    palette: { bg: '#F4F6F9', fg: '#16182B', accent: '#2E3192', accent2: '#E0A126' },
    font: { display: 'plex', body: 'plex' },
  },
  {
    slug: 'doublespace',
    name: 'DoubleSpace Beauty Salon',
    short: 'DoubleSpace',
    category: 'Salão de Beleza',
    group: 'Saúde & Beleza',
    tagline: 'Nails · Cosmetology · Barber — o teu espaço de beleza em Benfica.',
    location: 'Estr. de Benfica 706A · Lisboa',
    year: '2025',
    palette: { bg: '#F6F1EC', fg: '#1B1714', accent: '#C06A52', accent2: '#A98DA0' },
    font: { display: 'bricolage', body: 'sans' },
  },
  {
    slug: 'linda-mulher',
    name: 'Linda Mulher Studio',
    short: 'Linda Mulher',
    category: 'Extensões Capilares',
    group: 'Saúde & Beleza',
    tagline: 'Extensões de cabelo 100% humano. Luxo e transformação em Lisboa.',
    location: 'R. Polo Norte 18D · Lisboa',
    year: '2025',
    palette: { bg: '#FBF4F7', fg: '#2A1620', accent: '#CC0C78', accent2: '#B08D3C' },
    font: { display: 'cormorant', body: 'jost' },
  },
  {
    slug: 'imobenfica',
    name: 'Imobenfica by Marta Pereira',
    short: 'Imobenfica',
    category: 'Imobiliária',
    group: 'Serviços & Negócios',
    tagline: 'Especialistas reconhecidos no mercado imobiliário de Benfica.',
    location: 'Av. Gomes Pereira 28B · Benfica',
    year: '2025',
    palette: { bg: '#F6F3EC', fg: '#241019', accent: '#7A1B47', accent2: '#5A1235' },
    font: { display: 'playfair', body: 'sans' },
  },

  // ── Avenidas Novas (Saldanha / Campo Pequeno / Av. da República) ──────────────
  {
    slug: 'factiva',
    name: 'Factiva — Contabilidade e Gestão',
    short: 'Factiva',
    category: 'Contabilidade',
    group: 'Serviços & Negócios',
    zone: 'Avenidas Novas',
    tagline: 'Contabilidade e gestão de confiança, nas Avenidas Novas.',
    location: 'Av. da República 47 · Saldanha',
    year: '2025',
    palette: { bg: '#F4F7FB', fg: '#14233B', accent: '#2563B0', accent2: '#18A07A' },
    font: { display: 'jakarta', body: 'sans' },
  },
  {
    slug: 'nova-dentismed',
    name: 'Nova Dentismed — Clínica Médico-Dentária',
    short: 'Nova Dentismed',
    category: 'Clínica Dentária',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'O seu sorriso em mãos especializadas.',
    location: 'Av. da República 56 · Saldanha',
    year: '2025',
    palette: { bg: '#F0F8F9', fg: '#0E2A33', accent: '#0E8E9E', accent2: '#3FB6A0' },
    font: { display: 'outfit', body: 'sans' },
  },
  {
    slug: 'value-advantage',
    name: 'Value Advantage — Contabilidade e Gestão',
    short: 'Value Advantage',
    category: 'Contabilidade',
    group: 'Serviços & Negócios',
    zone: 'Avenidas Novas',
    tagline: 'Contabilidade que acrescenta valor ao seu negócio.',
    location: 'Av. 5 de Outubro 151 · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F5F8F6', fg: '#102A23', accent: '#2E7D6A', accent2: '#B68A2E' },
    font: { display: 'manrope', body: 'sans' },
  },
  {
    slug: 'artz-hair',
    name: 'Art.Z Hair & Experience',
    short: 'Art.Z Hair',
    category: 'Cabeleireiro & Beleza',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Hair & Experience — beleza com assinatura.',
    location: 'Av. Luís Bívar 93 · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F7F3EF', fg: '#1A1614', accent: '#A8854E', accent2: '#6E5A52' },
    font: { display: 'cormorant', body: 'jost' },
  },
  {
    slug: 'suelen-cunha',
    name: 'Advogada Suelen Cunha',
    short: 'Suelen Cunha',
    category: 'Advocacia',
    group: 'Serviços & Negócios',
    zone: 'Avenidas Novas',
    tagline: 'Advocacia próxima, rigorosa e dedicada a si.',
    location: 'Campo Pequeno 2 · Lisboa',
    year: '2025',
    palette: { bg: '#F8F5F0', fg: '#1E1B2E', accent: '#7A2E3B', accent2: '#B0913F' },
    font: { display: 'playfair', body: 'sans' },
  },
  {
    slug: 'tantos-livros',
    name: 'Tantos Livros, Livreiros',
    short: 'Tantos Livros',
    category: 'Livraria',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Uma livraria com tantos livros e tantas histórias.',
    location: 'Av. Marquês de Tomar 1B · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F6F1E8', fg: '#2A2018', accent: '#B5532E', accent2: '#3E6B57' },
    font: { display: 'fraunces', body: 'sans' },
  },
  {
    slug: 'dentofisis',
    name: 'Clínica Dentária DentoFisis',
    short: 'DentoFisis',
    category: 'Clínica Dentária',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Saúde dentária com rigor e proximidade.',
    location: 'R. de Entrecampos 5D · Lisboa',
    year: '2025',
    palette: { bg: '#F1F7F5', fg: '#0F2A2A', accent: '#1F9E8E', accent2: '#5BB6C9' },
    font: { display: 'manrope', body: 'sans' },
  },
  {
    slug: 'clinica-das-avenidas',
    name: 'Clínica das Avenidas — Dr. Rui Delfim',
    short: 'Clínica das Avenidas',
    category: 'Medicina Dentária',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Medicina dentária de confiança, nas Avenidas Novas.',
    location: 'Av. das Forças Armadas 4 · Lisboa',
    year: '2025',
    palette: { bg: '#F2F6FC', fg: '#102438', accent: '#2C7BE5', accent2: '#36B0A6' },
    font: { display: 'outfit', body: 'sans' },
  },
  {
    slug: 'pmm-advogados',
    name: 'Pereira Mouta Mendes & Associados',
    short: 'PMM Advogados',
    category: 'Sociedade de Advogados',
    group: 'Serviços & Negócios',
    zone: 'Avenidas Novas',
    tagline: 'Ao serviço dos seus direitos, com rigor.',
    location: 'R. Dr. Bastos Gonçalves 5B · Lisboa',
    year: '2025',
    palette: { bg: '#F5F6F8', fg: '#16203A', accent: '#1E3A5F', accent2: '#A6802E' },
    font: { display: 'archivo', body: 'sans' },
  },
  {
    slug: 'vitorias-beauty',
    name: 'Vitorias Beauty — Cabeleireiro Saldanha',
    short: 'Vitorias Beauty',
    category: 'Cabeleireiro & Beleza',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Cabeleireiro e beleza no coração do Saldanha.',
    location: 'Av. Defensores de Chaves 3A · Saldanha',
    year: '2025',
    palette: { bg: '#FBF2F4', fg: '#25131B', accent: '#C84A78', accent2: '#C79A3E' },
    font: { display: 'bricolage', body: 'sans' },
  },
  {
    slug: 'o-rialva',
    name: 'O Rialva — Restaurante',
    short: 'O Rialva',
    category: 'Restaurante Português',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Cozinha portuguesa de sempre, na Duque de Ávila.',
    location: 'Av. Duque de Ávila 2B · Saldanha',
    year: '2025',
    palette: { bg: '#F7F2EA', fg: '#2A1A14', accent: '#8A2B2B', accent2: '#C89A3E' },
    font: { display: 'fraunces', body: 'sans' },
  },
  {
    slug: 'good-company-books',
    name: 'Good Company Books',
    short: 'Good Company Books',
    category: 'Livraria',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Boa companhia, bons livros.',
    location: 'Av. Visc. de Valmor 2 · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F5F1E9', fg: '#1E2A23', accent: '#2E5D45', accent2: '#C08A2E' },
    font: { display: 'cormorant', body: 'sans' },
  },
  {
    slug: 'tasca-do-fonseca',
    name: 'Tasca do Fonseca',
    short: 'Tasca do Fonseca',
    category: 'Restaurante & Petiscos',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Petiscos e tradição à mesa.',
    location: 'R. Direita de Palma 11 · Lisboa',
    year: '2025',
    palette: { bg: '#F7F1E7', fg: '#291C14', accent: '#A33B2E', accent2: '#C7A14E' },
    font: { display: 'fraunces', body: 'sans' },
  },
  {
    slug: 'tasquinha-dos-grelhados',
    name: 'Tasquinha dos Grelhados',
    short: 'Tasquinha dos Grelhados',
    category: 'Restaurante / Grelhados',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Grelhados na brasa, sabor de Lisboa.',
    location: 'Rua de Ponta Delgada 32 · Lisboa',
    year: '2025',
    palette: { bg: '#F6F1EA', fg: '#26201B', accent: '#C24A2C', accent2: '#3E5742' },
    font: { display: 'oswald', body: 'sans' },
  },
  {
    slug: 'cabeleireiro-nogueira',
    name: 'Cabeleireiro Nogueira',
    short: 'Cabeleireiro Nogueira',
    category: 'Cabeleireiro',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Cabeleireiro de excelência, há gerações.',
    location: 'Av. Visc. de Valmor 61 · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F7F4EF', fg: '#1C1A17', accent: '#9A7B4F', accent2: '#46423E' },
    font: { display: 'cormorant', body: 'jost' },
  },
  {
    slug: 'estetica-nice',
    name: 'Estética Nice',
    short: 'Estética Nice',
    category: 'Estética & Beleza',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Estética e bem-estar nas Avenidas Novas.',
    location: 'Av. de Madrid 5B · Lisboa',
    year: '2025',
    palette: { bg: '#FBF4F1', fg: '#2A1A18', accent: '#C0795E', accent2: '#C2A35E' },
    font: { display: 'cormorant', body: 'jost' },
  },
  {
    slug: 'neia-souza',
    name: 'Neia Souza — Cabeleireiro & Estética',
    short: 'Neia Souza',
    category: 'Cabeleireiro & Estética',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Cabeleireiro e estética ao seu cuidado.',
    location: 'Av. Júlio Dinis 6A · Avenidas Novas',
    year: '2025',
    palette: { bg: '#FAF3F5', fg: '#241620', accent: '#A8527E', accent2: '#C99A6A' },
    font: { display: 'bricolage', body: 'sans' },
  },
  {
    slug: 'alex-cabeleireiro',
    name: 'Alex — Cabeleireiro, Makeup e Estética',
    short: 'Alex',
    category: 'Cabeleireiro & Makeup',
    group: 'Saúde & Beleza',
    zone: 'Avenidas Novas',
    tagline: 'Cabelo, makeup e estética num só espaço.',
    location: 'Av. de Madrid 6B · Lisboa',
    year: '2025',
    palette: { bg: '#F8F2F5', fg: '#241622', accent: '#B83C72', accent2: '#3A2E38' },
    font: { display: 'bricolage', body: 'sans' },
  },
  {
    slug: 'good-company-cafe',
    name: 'Good Company Café',
    short: 'Good Company Café',
    category: 'Café',
    group: 'Comércio & Restauração',
    zone: 'Avenidas Novas',
    tagline: 'Café, conversa e boa companhia.',
    location: 'Av. Visc. de Valmor 2A · Avenidas Novas',
    year: '2025',
    palette: { bg: '#F4EFE7', fg: '#27201A', accent: '#6F4A2E', accent2: '#2E5D45' },
    font: { display: 'cormorant', body: 'sans' },
  },
  {
    slug: 'aml-advogados',
    name: 'AML — Sociedade de Advogados',
    short: 'AML Advogados',
    category: 'Sociedade de Advogados',
    group: 'Serviços & Negócios',
    zone: 'Avenidas Novas',
    tagline: 'Advogados ao serviço das pessoas e das empresas.',
    location: 'Av. Barbosa du Bocage 87 · Lisboa',
    year: '2025',
    palette: { bg: '#F6F5F2', fg: '#1A2230', accent: '#33485F', accent2: '#9A7B3A' },
    font: { display: 'fraunces', body: 'sans' },
  },
]

/**
 * APPS — lazy-loaded site applications, keyed by slug.
 * A site appears as "em construção" on the grid until its entry is wired here.
 * (Sites são ligados à medida que ficam prontos.)
 */
export const APPS = {
  filipitsch: lazy(() => import('./filipitsch/index.jsx')),
  'reparacao-tv-lisboa': lazy(() => import('./reparacao-tv-lisboa/index.jsx')),
  'pedrita-studio': lazy(() => import('./pedrita-studio/index.jsx')),
  'tecnico-frio': lazy(() => import('./tecnico-frio/index.jsx')),
  nipolandia: lazy(() => import('./nipolandia/index.jsx')),
  'farol-vibrante': lazy(() => import('./farol-vibrante/index.jsx')),
  fornoportugal: lazy(() => import('./fornoportugal/index.jsx')),
  iri: lazy(() => import('./iri/index.jsx')),
  'conta-100': lazy(() => import('./conta-100/index.jsx')),
  'rui-dinis': lazy(() => import('./rui-dinis/index.jsx')),
  'linda-mulher': lazy(() => import('./linda-mulher/index.jsx')),
  imobenfica: lazy(() => import('./imobenfica/index.jsx')),
  doublespace: lazy(() => import('./doublespace/index.jsx')),
  factiva: lazy(() => import('./factiva/index.jsx')),
  'nova-dentismed': lazy(() => import('./nova-dentismed/index.jsx')),
  'pmm-advogados': lazy(() => import('./pmm-advogados/index.jsx')),
  'value-advantage': lazy(() => import('./value-advantage/index.jsx')),
  'artz-hair': lazy(() => import('./artz-hair/index.jsx')),
  'suelen-cunha': lazy(() => import('./suelen-cunha/index.jsx')),
  'tantos-livros': lazy(() => import('./tantos-livros/index.jsx')),
  'clinica-das-avenidas': lazy(() => import('./clinica-das-avenidas/index.jsx')),
  dentofisis: lazy(() => import('./dentofisis/index.jsx')),
}

export const sites = META.map((m) => ({
  ...m,
  zone: m.zone || 'Calçada do Tojal',
  App: APPS[m.slug] || null,
}))

export const groups = ['Todos', ...Array.from(new Set(META.map((m) => m.group)))]

export const zones = ['Todas', 'Calçada do Tojal', 'Avenidas Novas']

export function getSite(slug) {
  return sites.find((s) => s.slug === slug) || null
}
